version: '3.8'


services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: mongo:8.0.3
    container_name: mongodb
    ports:
      - "27017:27017"
