services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
    env_file:
      - D:/Programing/Golang/apis/api_models3D/.env
